### ISSUE TITLE
Using as.tibble() results in warning

### ISSUE THREAD

**Issue by juliasilge** [koalaverse/vip#101]
Thank you so much for your work on this fantastic package! 🙌 

Using `as.tibble()` as in this line:
https://github.com/koalaverse/vip/blob/bb6294c433af4824c11b779dd101086d0b9084b9/R/vi_model.R#L1322
results in warnings such as this after users call `vip()`:
```
Warning message:
`as.tibble()` is deprecated as of tibble 2.0.0.
Please use `as_tibble()` instead.
The signature and semantics have changed, see `?as_tibble`.
```

**Comment by bradleyboehmke** [comment]
Thanks @juliasilge!  This has been updated in the [issue101 branch](https://github.com/koalaverse/vip/tree/issue101) and will be merged into master once @bgreenwell OKs.

**Comment by juliasilge** [comment]
Sounds great!
