### ISSUE TITLE
Add variable importance for survival models (survivalmodels package)

### ISSUE THREAD

**Issue by ilagith** [koalaverse/vip#121]
Thank you a lot for this beautiful package!

It would be great to compute variable importance for models implemented through survivalmodels package, in partiucular for neural networks such as deepsurv. 
 
Thanks!

**Comment by bgreenwell** [comment]
Hi @ilagith, thanks for the note, and glad you find the package useful. In theory  you should  be able to use one of the model-agnostic approached (e.g., `method="permute"`). The  challenge is in defining the  prediction wrapper and corresponding metric function. For example,  in  ordinary regression, you might define the metric as RMSE. For  survival models,  I think the Brier score is an appropriate metric in  some cases. If you have a simple example with code, I can try to put together a solution. WOuld be nice for the documentation as well or a vignette.

**Comment by bgreenwell** [comment]
@ilagith feel free to reopen if you share an example and still would like this functionality.
