### ISSUE TITLE
Remove `vint()` and `add_sparklines()` functions?

### ISSUE THREAD

**Issue by bgreenwell** [koalaverse/vip#137]
@bradleyboehmke what do you think about removing these? They seem a bit out of scope for the package and the former is not very computationally feasible for most real problems?

**Comment by bradleyboehmke** [comment]
I would agree.  `add_sparklines` was more of a nice-to-have-for-reporting that we may have used a couple times but keeping it in and supporting long-term doesn't seem necessary.

As for `vint`, it seems a little more aligned to the intent of the package but if there are other packages that specialize in interaction effects then probably best to rely on them and keep this package more focused.

**Comment by bgreenwell** [comment]
Will circle back to vint() once the other changes are in. At the least, would just need a rewrite to remove the plyr dependency.

**Comment by franzbischoff** [comment]
Just made a new Frankenstein of it. Somewhat more information during the process...

Worth to mention that the bottleneck is on `pdp::partial`, proportional to the given "training data", here just `data`. If we would like to "test" the process before the long run, we can subsample the "training data"


```r
vint <- function(object, feature_names, data, type, n_jobs = 1, ...) {
  checkmate::qassert(feature_names, "S+")

  all_pairs <- utils::combn(feature_names, m = 2) # two by two
  all_pairs <- purrr::array_tree(all_pairs, 2)

  cli::cli_alert_info("Computing the importances of {length(all_pairs)} combinations.")

  if (n_jobs == 1) {
    future::plan(future::sequential)
  } else {
    future::plan(future::multisession, workers = n_jobs)
  }

  progressr::with_progress(
    {
      p <- progressr::progressor(along = all_pairs)

      p("starting", amount = 0)
      # computing partials
      parts <- furrr::future_map(all_pairs, function(x, ...) {
        pd <- pdp::partial(object, pred.var = x, ...)
        p("computing partials")
        pd
      }, train = data, type = type, .options = furrr::furrr_options(seed = TRUE)) # , scheduling = 1))
    },
    handlers = progressr::handler_progress(format = "[:bar] :percent :eta :message")
  )

  cli::cli_alert_info("Gathering statistics.")
  # compute the sd of the partials
  ints <- purrr::map_vec(parts, function(x) {
    mean(c(
      stats::sd(tapply(x$yhat, INDEX = x[[1]], FUN = stats::sd)),
      stats::sd(tapply(x$yhat, INDEX = x[[2]], FUN = stats::sd))
    ))
  })

  pairs <- purrr::transpose(all_pairs)

  res <- tibble::tibble(
    "Variables" = paste0(pairs[[1]], "*", pairs[[2]]),
    "Interaction" = ints
  )

  return(res)
}
```

**Comment by bgreenwell** [comment]
I decided to remove both from this package, since they do not explicitly focus on variable importance. I would not be opposed to adding back a more efficient version of `vint()` in a future update, but for now, the original version will live on in the [moreparty](https://cran.r-project.org/package=moreparty) package.
