### ISSUE TITLE
Errors running vi_permute in parallel

### ISSUE THREAD

**Issue by balraadjsings** [koalaverse/vip#144]
Using `vi_permute()` in parallel with certain tidymodels objects returns errors while running it with `parallel=FALSE` runs just fine. I've noticed this for BART and Cubist rules models only so far, other parsnip objects work fine.

If I run the following code: 
`pred <- function(object, newdata) {
  predict(object, newdata)
}`

`registerDoParallel(cores = 4)`

`bart_model %>% extract_fit_parsnip() %>% 
  vi_permute(target="outcome",
             metric="rsquared",
             train=train,
             pred_wrapper=pred,
             nsim=10,
             parallel=TRUE)`

The following error (and warnings) gets returned: 
`Error in do.ply(i) : 
  task 1 failed - "no applicable method for 'predict' applied to an object of class "c('_bart', 'model_fit')""`
`In addition: Warning messages:
1: <anonymous>: ... may be used in an incorrect context: ‘.fun(piece, ...)’
2: <anonymous>: ... may be used in an incorrect context: ‘.fun(piece, ...)’`

Judging from the error it has something to do with the function passed to pred_wrapper but it works fine for other parsnip models and also with parallel=FALSE. Any ideas on how to fix this issue?

**Comment by brandongreenwell-8451** [comment]
@balraadjsings I'm glad you were able to find an answer to your question. Note that we'll be pushing a new version to CRAN soon and this behavior will slightly change. In short, we've the dependency on **plyr**, so in the future you'll call the `.packages` argument directly. I'll make a note to add this to the examples and new package docs.

**Comment by bgreenwell** [comment]
Made a note in the documentation for `vi_permute()`. Thanks again for the call out!
