### ISSUE TITLE
vi_permute reproducibility when using parallel processing 

### ISSUE THREAD

**Issue by balraadjsings** [koalaverse/vip#145]
Running `vi_permute()` with parallel=TRUE is not reproducible when using `set.seed` prior to running the function (have not tried other functions in the vip package but it'll probably also apply to them). 

It seems `set.seed()` gets ignored while using parallel processing. Like my previous post, this also seems to be related to foreach. A fix I've found to work for now is to use the package `doRNG` instead of the `set.seed()` function e.g.: 
`registerDoRNG(seed = 123)`  and then run `vi_permute()` with parallel=TRUE

This might be something to note in the documentation for when parallelization is used?

**Comment by bgreenwell** [comment]
Thanks @balraadjsings, added a link to your suggestion in the `vi_permute` help page! (Will push to the devel branch soon.)
