### ISSUE TITLE
Plans for CRAN?

### ISSUE THREAD

**Issue by mitch-tanney-coterie** [koalaverse/vip#153]
First and foremost, thanks for maintaining this package. We use it throughout several modeling pipelines that also leverage the `tidymodels` framework.

We noticed recently that `vip()` was [removed from CRAN](https://cran.r-project.org/web/packages/vip/index.html). Is the current status below temporary due to CRAN-imposed requirements, or are you no longer planning to maintain this package?

![image](https://github.com/koalaverse/vip/assets/110246571/c5b87f66-304b-4a77-a8c7-a2293dba89cc)

**Comment by bgreenwell** [comment]
Well, this is news to me as we had just updated the package a few weeks ago and it was accepted to CRAN. I will look into this shortly, but yes, temporary.

**Comment by mitch-tanney-coterie** [comment]
Sounds good, and thanks for the prompt reply.

**Comment by mitokic** [comment]
I'd like to add this package into my R packaged called finnts, looking forward to seeing this get back onto cran soon so I can ship my package update. Thanks team.

**Comment by bgreenwell** [comment]
Thanks @mitokic, resubmitting to CRAN as we speak, so hopefully fixed over the weekend!

**Comment by bgreenwell** [comment]
Back on CRAN! Will take a day or two for the Max/Windows binaries to appear. Apologies for the mishap! Will leave this open until all the binaries are back up.

**Comment by mitokic** [comment]
Thank you!

**Comment by mitch-tanney-coterie** [comment]
> Thank you!

Agreed. Thanks for moving quickly on this, @bgreenwell.

**Comment by mitokic** [comment]
@bgreenwell why dpes the latest package require R 4.1 or greater?

**Comment by bgreenwell** [comment]
@mitokic I suppose it’s not a “strong” requirement but I wanted to lose the magrittr dependency and R 4.1 introduced the native pipe operator. I suppose this dependency could be relaxed in the next version if needed?

**Comment by mitokic** [comment]
@bgreenwell no worries I think I can work around it since I'd like to add vip into the suggests portion of my finnts package. Thanks though!
