### ISSUE TITLE
Switch to `abbreviate()` for `truncate_feature_names`

### ISSUE THREAD

**Issue by bgreenwell** [koalaverse/vip#29]

**Comment by bradleyboehmke** [comment]
Changed `truncate_feature_names` to `abbreviate_feature_names`.  See commit [1c96fea2ad343ac321065f8fc4b7ebf2703b3b21](https://github.com/koalaverse/vip/commit/1c96fea2ad343ac321065f8fc4b7ebf2703b3b21)
