### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by bgreenwell** [koalaverse/vip#33]
Should not be hard to reach >90% test coverage.

**Comment by bgreenwell** [comment]
@bradleyboehmke let's crank out some tests! I've fixed up `vi_permute()` to where it works pretty well across the board (some argument name changes, etc.). But **vip** needs more tests before the next CRAN update. I've standardized the tests for `get_feature_names()`. 

@bfgray3 Feel free to help out if you can (or are interested) and be sure to add your name to the list of package authors in `DESCRIPTION` for all the awesome work you've done!

**Comment by bfgray3** [comment]
Hey guys, school just started up for the fall so I'll be a little busier coming up but I'd like to help out with some tests (often doing open source is much more fun than homework).  I'll add myself to the DESCRIPTION when I write some; thanks!

**Comment by bgreenwell** [comment]
Awesome! Feel free to contribute when you can, I've added you as a collaborator with write access, so you should be able to push directly to this repo without PRs. Good luck with classes!
