### ISSUE TITLE
Local variable importance measures?

### ISSUE THREAD

**Issue by bradleyboehmke** [koalaverse/vip#45]
Are we interested in incorporating our own measures for local vip (i.e. Shapley, LIME)?

**Comment by bgreenwell** [comment]
I'm not opposed to the idea. Just dependence how much coding is involved, etc.! I need to give another hard look at LIME and Shapley. Am also interested in seeing how using the Stdev of the indivudal ICE curves compares to other local methods (though, these would always be positive values)...

**Comment by bgreenwell** [comment]
Seems out of scope at the moment, but related to [this issue](https://github.com/koalaverse/vip/issues/26). Closing for now.
