### ISSUE TITLE
Error in vint() function

### ISSUE THREAD

**Issue by stat17-hb** [koalaverse/vip#66]
Hi, I'm trying to reproduce results of the link below:
https://koalaverse.github.io/vip/articles/vip-interaction.html

However, I got an error message when I tried to run this part

`library(doParallel)  # any parallel backend supported by the foreach package should work`
`registerDoParallel(cores = 4)  # use four cores`
`int <- vint(nn, feature_names = paste0("x.", 1:10), parallel = TRUE)`
`ggplot(int[1:10, ], aes(reorder(Variables, -Interaction), Interaction)) +`
 ` geom_col(width = 0.75) +`
 ` labs(x = "", y = "Interaction strength") +`
 ` theme(axis.text.x = element_text(angle = 45, vjust = 1)) +`
 ` theme_light()`

Error in do.ply(i) : task 1 failed - "object 'nn' not found"
7. stop(simpleError(msg, call = expr))
6. e$fun(obj, substitute(ex), parent.frame(), e$data)
5. foreach::`%dopar%`(fe, do.ply(i))
4. llply(.data = .data, .fun = .fun, ..., .progress = .progress, .inform = .inform, .parallel = .parallel, .paropts = .paropts)
3. laply(.data = pieces, .fun = .fun, ..., .progress = .progress, .inform = .inform, .drop = .drop, .parallel = .parallel, .paropts = .paropts)
2. plyr::aaply(all.pairs, .margins = 2, .progress = progress, .parallel = parallel, .paropts = paropts, .fun = function(x) { pd <- pdp::partial(object, pred.var = x, ...) mean(c(stats::sd(tapply(pd$yhat, INDEX = pd[[x[1L]]], ...
1. vint(nn, feature_names = paste0("x.", 1:10), parallel = TRUE)

It seems to be due to some mistakes in foreach loop related to object 'nn'.
Could you check out the code of vint() function?

**Comment by bgreenwell** [comment]
Hi @stat17-hb, it seems you do not have the nn object defined anywhere. Did you perhaps forget to run that piece of the code? See below.

```r
# Fit a neural network to simulated data
set.seed(103)
nn <- nnet(y ~ ., data = trn, size = 8, linout = TRUE, decay = 0.01,
           maxit = 1000, trace = FALSE)
```

**Comment by stat17-hb** [comment]
Thank you for your comment! But I certainly ran above code.

```r
# Fit a neural network to simulated data
set.seed(103)
nn <- nnet(y ~ ., data = trn, size = 8, linout = TRUE, decay = 0.01,
           maxit = 1000, trace = FALSE)
```

I found a way to solve this problem.

```r
vint <- function(object, feature_names, progress = "none", parallel = FALSE,
                 paropts = NULL) {
  warning("This function is experimental, use at your own risk!", call. = FALSE)
  all.pairs <- utils::combn(feature_names, m = 2)
  **clusterExport(cl=cl, varlist=c("nn","trn"), envir=environment()) # added**
  ints <- plyr::aaply(
    all.pairs, .margins = 2, .progress = progress, .parallel = parallel,
    **.paropts = list(.packages="nnet"),  # added**
    .fun = function(x) {
      pd <- pdp::partial(object, pred.var = x)
      mean(c(
        stats::sd(tapply(pd$yhat, INDEX = pd[[x[1L]]], FUN = stats::sd)),
        stats::sd(tapply(pd$yhat, INDEX = pd[[x[2L]]], FUN = stats::sd))
      ))
  })
  ints <- data.frame(
    "Variables" = paste0(all.pairs[1L, ], "*", all.pairs[2L, ]),
    "Interaction" = ints
  )
  ints <- ints[order(ints["Interaction"], decreasing = TRUE), ]
  tibble::as_tibble(ints)
}
```

**Comment by bgreenwell** [comment]
Ahh, correct, I was using the multicore functionality only available on Unix systems. I’ll update the example in the vignette to support Windows (e.g., by passing the nnet 📦 via the .paropts argument in vint). Wine be able to get to it for a couple days though!
