### ISSUE TITLE
Change default behavior for printing importance type in `vip()` axis label?

### ISSUE THREAD

**Issue by bgreenwell** [koalaverse/vip#76]
For example, do we really need to print `(nsubsets)` for the output from a MARS model below?

![image](https://user-images.githubusercontent.com/3777755/68413544-7765ca00-015c-11ea-9e4f-5be60ed00e13.png)

**Comment by bradleyboehmke** [comment]
Does it make sense to add a parameter (i.e. `include_type = FALSE`) that allows the user to turn this on and off? I would set the default to to FALSE but this allows an easy approach for folks uncertain to which importance method is being used by their model to easily get that information.

**Comment by bgreenwell** [comment]
Will add this to the next release!

**Comment by bradleyboehmke** [comment]
This was merged into master with PR #78 so we can close this issue and I can delete the issue_76 branch, right?
