### ISSUE TITLE
Simplify specification of aesthetics in `vip()`

### ISSUE THREAD

**Issue by bgreenwell** [koalaverse/vip#80]
For example,

```r
vip(fit, type = "dotplot", aesthetics = list(size = 3))
```
instead of 
```r
vip(fit, type = "dotplot", size = 3)
```

**Comment by bradleyboehmke** [comment]
What if - rather than do a hard backward compatibility break with branch issue-79-80 we do deprecation warning?  This would require us to retain more code since we'd have to still allow aesthetics as they were stated in current versions plus allow the new aesthetics option but it wouldn't force a hard version break. 

Just an option if we're worried about ticking off early adopters of the package with a hard version break.

**Comment by bgreenwell** [comment]
Seems reasonable. It’ll take a bit of code but I’ll work on it!

**Comment by bgreenwell** [comment]
@bradleyboehmke got it. The old approach should still work, but with a warning that these features will be removed in the next planned version.

Example:

```r
# Load required packages
library(ggplot2)  # for `aes_string()` function

# Load the sample data
data(mtcars)

# Fit a linear regression model
model <- lm(mpg ~ ., data = mtcars)

# Construct variable importance plots
p1 <- vip(model)
p2 <- vip(model, mapping = aes_string(color = "Sign"))
p3 <- vip(model, type = "dotplot")
p4 <- vip(model, type = "dotplot", mapping = aes_string(color = "Variable"),
          aesthetics = list(size = 3))
grid.arrange(p1, p2, p3, p4, nrow = 2)

# Make sure old approach still works, alebit with a warning
vip(model, bar = FALSE)
vip(model, bar = FALSE, color = "red")
vip(model, bar = TRUE, color = "red", fill = "green")
vip(model, bar = TRUE, color = "red", fill = "green", width = 1/3)
```

**Comment by bgreenwell** [comment]
Try to break it if you can and I'll merge when we're happy with it.

**Comment by bradleyboehmke** [comment]
The updates look good. Not sure if you realize or not but the `type` arguments you provided don't do anything (older version??).

i.e.:
```r
vip(model, type = "dotplot")
```

**Comment by bgreenwell** [comment]
Oops, forgot to mention. I renamed the new `type` argument to `geom` so that it doesn't conflict with the `type` argument to `vi_model()` which can be passed via `...` in `vi()` and `vip()`. I updated the docs in `?vip::vip` quite a bit make it clear.
