### ISSUE TITLE
vip with 

### ISSUE THREAD

**Issue by vnijs** [koalaverse/vip#84]
Having some trouble with `vip` when method is not set to "model". This issue seems to pops up if there are categorical features in the model. I tried `attr(mod$terms, "term.labels")` in the `get_feature_names.nnet` function and that stops the error messages for `ice` and `pdp`. However, now the `vi` values are all zero which is probably not correct.

```
> mod <- nnet::nnet(Sepal.Length ~ ., size = 2, data = iris)
# weights:  15
initial  value 4310.212032 
final  value 3620.850000 
converged
> vip(mod, train = iris, method = "model")
> vip(mod, train = iris, method = "pdp")
Error in partial.default(object, pred.var = feature_name, ...) : 
  Speciesversicolor not found in the training data.
> vip(mod, train = iris, method = "ice")
Error in partial.default(object, pred.var = feature_name, ice = TRUE,  : 
  Speciesversicolor not found in the training data.
> vip(mod, train = iris, target = "Sepal.Length", method = "permute")
Error in UseMethod("get_default_metric") : 
  no applicable method for 'get_default_metric' applied to an object of class "c('nnet.formula', 'nnet')"
```

**Comment by bgreenwell** [comment]
Hi @vnijs thanks for posting the two issues. I’ll have a look early next week when I’m back from vacation. Happy holidays!

**Comment by bgreenwell** [comment]
Hi @vnijs thanks for again for posting the issue. You are correct in that `attr(mod$terms, "term.labels")` is a better way for grabbing the feature names from an `"nnet"` object, but this will only work when using the formula interface provided by **nnet** (which is reasonable I think). I'll fix this in the next release and throw a better error message when the feature names cannot be found. FYI, the importance scores are all zero after your fix bc you did not specify `linout = TRUE` in the call to `nnet::nnet()`, which you should almost always do when the response is continuous (i.e., a regression problem). For now, here's a simple fix:

```r
mod <- nnet::nnet(Sepal.Length ~ ., size = 2, data = iris, linout = TRUE)
xnames <- setdiff(names(iris), "Sepal.Length")
vip(mod, train = iris, method = "pdp", feature_names = xnames)
```

**Comment by bgreenwell** [comment]
Fixed in latest PR.
