### ISSUE TITLE
Add Shapley-based importance

### ISSUE THREAD

**Issue by bgreenwell** [koalaverse/vip#87]
Use **fastshap** for Shapley-based feature importance. Future versions of **fastshap** will utilize TreeSHAP for fast results when applied to certain models like xgboost and lightgbm.

**Comment by bradleyboehmke** [comment]
Should we have a vi_shap method that allows both fast shap and also tree shap methods?  Meaning, it can leverage both fastshap and also allow xgboost's (and any other models) that have built-in shapley computations (shortcut to [this](https://bradleyboehmke.github.io/HOML/iml.html#xgboost-and-built-in-shapley-values)).

**Comment by bgreenwell** [comment]
My thought is that **fastshap** will just default to using TreeSHAP in the next release so we’d just use that (consistent) interface! But yes, I like the idea of vi_shap() as the workhorse underneath. Ideally it would just call fastshap::explain(tree_mod, exact = TRUE, ...) or something to that effect.

**Comment by bgreenwell** [comment]
Initial support incorporated.
